@baseUrl = http://127.0.0.1:9393
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30


GET {{baseUrl}}/users/


POST {{baseUrl}}/users/register
Content-Type: {{contentType}}

{
  "fullname" : "Luca Verdi",
  "username" : "lverdi",
  "email": "lverdi@test.com",
  "password" : "lverdi@123",
  "role" : "docente"
}
